name: Publish

on:
  push:
    branches: ["tg/autorelease"]  # FIXME: testing
    tags: ["*.*.*"]


jobs:
  # FIXME: check that our git tag matches the version in pyproject.toml
  
  call-ci:
    uses: ./.github/workflows/ci.yml

  build:
    runs-on: ubuntu-latest
    needs: [call-ci]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv build
